#############################
######### DEFAULT ###########
#############################

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.5'

gem 'rails', '~> 5.2.3'
gem 'puma', '~> 3.11'
gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

##############################
####### SETUP GEMS ###########
##############################

gem 'active_model_serializers', '~> 0.10.2'
gem 'figaro'
gem 'pg', '>= 0.18', '< 2.0'
gem 'bcrypt', '~> 3.1.7'
gem 'simple_command'
gem 'jwt'
gem 'rack-attack'
gem 'rack-cors'
gem 'ransack'
gem 'kaminari'